redis_resque:
  test: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  development: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  production: ec2-3-91-163-59.compute-1.amazonaws.com:6379
redis_kudos:
  test: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  development: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  production: ec2-3-91-163-59.compute-1.amazonaws.com:6379
redis_general:
  test: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  development: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  production: ec2-3-91-163-59.compute-1.amazonaws.com:6379
redis_rollout:
  test: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  development: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  production: ec2-3-91-163-59.compute-1.amazonaws.com:6379
redis_autocomplete:
  test: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  development: ec2-3-91-163-59.compute-1.amazonaws.com:10509
  production: ec2-3-91-163-59.compute-1.amazonaws.com:6379
